Remove YAML from codebase
matthiasbeyer/cargo-changelog pull request #221
Opened 2023-04-28 20:44 UTC by TheNeikos

Closes #218

2023-04-28 20:46 UTC, TheNeikos commented
It didn't feel right to have the changelog as its own commit here? But I can split it out if you'd rather have that

2023-04-28 21:03 UTC, matthiasbeyer requested changes
Can you also convert the existing changelogs, so that the tool can read its own historical changelogs?

2023-04-28 21:03 UTC, matthiasbeyer commented on .changelog.toml
>  # Right now, only "yaml" is supported
This is not true anymore, is it?

2023-04-29 10:12 UTC, matthiasbeyer approved these changes

2023-04-29 10:12 UTC, matthiasbeyer commented on .changelogs/unreleased/2023-03-03T08_08_41_21078057.md
> +subject = "'\"Show\" subcommand'"
```suggestion
subject = "\"Show\" subcommand"
```

2023-04-29 10:12 UTC, matthiasbeyer commented on .changelogs/unreleased/2023-03-03T08_08_41_21078057.md
> +subject = "'\"Show\" subcommand'"
Just a nit, and not really important IMO.

2023-04-29 10:12 UTC, matthiasbeyer commented
bors merge

2023-04-29 10:19 UTC, merged